# Theme settings
doks:
    baseurl:
    color_theme: blue
    header:
        logo:
            text: Dr. Klein Ratenkredit
            image:
        nav:
            - item_name: API Dokumentation
              item_url: 'https://developer.drkleinservice.de/'
    footer:
        content:
            logo:
                text: Dr. Klein Ratenkredit
                image:
            copyright: Copyright &copy; 2020 - Dr. Klein Ratenkredit GmbH<br>All rights reserved.
    google_analytics:
        tracking_code: # Add your Google Analytics tracking code to activate Google Analytics

# SASS settings
sass:
    sass_dir: ./doks-theme/_sass
    style: :compressed

# Jekyll settings
layouts_dir: ./doks-theme/_layouts
includes_dir: ./doks-theme/_includes
exclude: [ 'README.md', 'CHANGELOG.md' ]
permalink: /:title/
